### ISSUE TITLE
Request: Options to build without minification & sourcemap generation

### ISSUE THREAD

**Issue by shellscape** [IonicaBizau/dist-it#9]
Title says it all. dist-it makes debugging shipped libs damn near impossibru without options to skip minification, and/or without sourcemaps.

**Comment by IonicaBizau** [comment]
I'm for it! There could be an option like `--no-minify` or so. Contributions are welcome! :four_leaf_clover:

**Comment by IonicaBizau** [comment]
In the latest version this is possible.

See the help output: https://github.com/IonicaBizau/dist-it#cloud-installation
